version: "3"
services:
  proxy:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
  postgres:
    image: postgres
    container_name: scramble_captain_pg
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    # ports:
    #   - 5432:5432
    volumes:
      - scramble_captain_db:/var/lib/postgresql/data
  frontend:
    stdin_open: true
    tty: true
    build:
      context: client
      args:
        SCRAMBLE_CAPTAIN_DOMAIN: ${SCRAMBLE_CAPTAIN_DOMAIN}
    image: scramble_captain_client
    command: yarn start
    # ports:
      # - 3000:3000
  backend:
    stdin_open: true
    tty: true
    build: server
    image: scramble_captain_server
    environment:
      - SECRET_KEY_BASE=1234
      - LUCKY_ENV=production
      - DATABASE_URL=postgresql://postgres@postgres/scramble_captain_production
      - SEND_GRID_KEY=unused
      - APP_DOMAIN=${SCRAMBLE_CAPTAIN_DOMAIN}
      - PORT=5000
    command: bash -c "./lucky db.create && ./lucky db.migrate && ./start_server"
    depends_on:
      - postgres
    # ports:
    #   - 5000:5000
    volumes:
      - scramble_captain_scrambles:/usr/src/scramble-captain-server/assets/scrambles
volumes:
  scramble_captain_db:
    driver: local
  scramble_captain_scrambles:
    driver: local